### ISSUE TITLE
Is the installation plugin offline?  I did a full reinstall of my Homebridge.  While trying to restore my backup configuration, the Onkyo plugin is not installing.  Please help!

### ISSUE THREAD

**Issue by Honosapiens** [ToddGreenfield/homebridge-onkyo#104]
**Confirm you have checked the WIKI for troubleshooting first**
_Fill out and check (`[x]`) the boxes which apply.
- Homebridge version:
- Plugin version:
- OS, including release name/version: 
- [ ] Homebridge-Onkyo installed via OS/distribution mechanisms
- [x] You installed using homebridge-config-ui-x
- [x] You enabled homebridge debug output

**Describe the bug**

**To Reproduce**
Information on your Onkyo receiver:
1. Model information

Information on your configuration:
1. Homebridge config

Information from the log:
1. Homebridge log file showing relevant information. Experienced users are asked to turn debug on.
Hint: The more information you provide here, the easier it is to help you. Do NOT provide only a single line showing an error message - give the develpers a chance by providing a full log.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Honosapiens** [comment]
Can't install the plugin.

**Comment by cbrandlehner** [comment]
When using homebridge-config-ui you will see some information on your environment on the 'status' page.
Please provide your system configuration.
As an example, mine is:
```
Node.js version: v14.16.0
Npm version: v6.14.11
...
```

**Comment by cbrandlehner** [comment]
Please reopen if the problem still persists.
