### ISSUE TITLE
question about zone

### ISSUE THREAD

**Issue by toshibochan** [ToddGreenfield/homebridge-onkyo#12]
I want control main zone, zone 2 and zone 3.
How I set in the config.json?

**Comment by ToddGreenfield** [comment]
You would add another accessory entry, like so-
"accessories": [
   {
   	"accessory": "Onkyo",
   	"name": "StereoMain",
   	"ip_address": "10.0.1.23",
   	"model" : "TX-NR609"
   },
   {
   	"accessory": "Onkyo",
   	"name": "StereoZone2",
   	"ip_address": "10.0.1.24",
   	"model" : "TX-NR609",
   	"zone" : "zone2"
   },   {
   	"accessory": "Onkyo",
   	"name": "StereoZone3",
   	"ip_address": "10.0.1.25",
   	"model" : "TX-NR609",
   	"zone" : "zone3"
   }
]

I do not personally use this functionality.  Another person contributed the PR so hopefully it works for you.

**Comment by toshibochan** [comment]
But have to be same IP address? Is only one onkyo.

**Comment by ToddGreenfield** [comment]
Yes, would be the same IP. I fixed the above.

**Comment by toshibochan** [comment]
Thanks I will try later!

**Comment by cbrandlehner** [comment]
Configuration changed in the 0.7.x codestream.
Please read documentation and reconfigure. Closing this as it does not apply to current codestream.
