### ISSUE TITLE
after update give me error

### ISSUE THREAD

**Issue by toshibochan** [ToddGreenfield/homebridge-onkyo#124]
[Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "ZVLQSTN"

**Comment by toshibochan** [comment]
[Onkyo] getInputState - INPUT QRY: ERROR - current i_state: 1

**Comment by toshibochan** [comment]
[Onkyo] eventError: ERROR (send_not_connected) Not connected, can't send data: "PWRQSTN"

**Comment by toshibochan** [comment]
[Onkyo] ERROR: Your configuration is missing the parameter "volume_type". Assuming "none".

**Comment by toshibochan** [comment]
"receivers": [
                {
                    "name": "Receiver main",
                    "model": "TX-RZ800",
                    "ip_address": "192.168.1.24",
                    "inputs": [
                        {
                            "input_name": "dvd",
                            "display_name": "Apple TV 4K"
                        },
                        {
                            "input_name": "video2",
                            "display_name": "Apple TV Japan"
                        },
                        {
                            "input_name": "video3",
                            "display_name": "Fire TV"
                        },
                        {
                            "input_name": "strm-box",
                            "display_name": "AppleTV Office"
                        }
                    ],
                    "filter_inputs": true,
                    "default_volume": 42,
                    "max_volume": 100,
                    "volume_dimmer": true,
                    "volume_speed": false,
                    "map_volume_100": true,
                    "poll_status_interval": "1000",
                    "zone": "main"

**Comment by toshibochan** [comment]
I can't control volume in the home app anymore

**Comment by cbrandlehner** [comment]
Can you please use the homebridge UI to configure the new "volume type" setting?

**Comment by toshibochan** [comment]
"volume type" setting?

have to update README config sample?

**Comment by toshibochan** [comment]
I use the Homebridge UI and now is working
thank you
