### ISSUE TITLE
Update of EISCP commands

### ISSUE THREAD

**Issue by tbelcher** [ToddGreenfield/homebridge-onkyo#13]
Is there a way to update the EISCP commands easily?  I found a post commenting on updated commands that now support other inputs in a Home Assistant thread.  Here's the body of that post?  IS this possible?

_In the master branch of the upstream repo here - https://github.com/miracle2k/onkyo-eiscp - there is an updated eiscp-commands.yaml and commands.py which includes support for the Streaming Box source as well as others. Grabbing the latest commands.py file here - https://github.com/miracle2k/onkyo-eiscp/blob/master/eiscp/commands.py - and replacing all occurrences of xrange with range so it works with Python3, I was able to drop this updated commands.py file in place of the current one in my HASS dependencies, and this fixes my issue. I'm not sure what the best way is to get the updated commands.py file into @danieljkemp's fork. Let me know if you want me to make a pull request with the latest file._

https://github.com/home-assistant/home-assistant/issues/6022

**Comment by ToddGreenfield** [comment]
Not that I have found. Feel free to do a pull request though.

**Comment by cbrandlehner** [comment]
@tbelcher this repository is still alive.
We would appreciate if you can help by contributing to the code.
