### ISSUE TITLE
installation error - need help

### ISSUE THREAD

**Issue by pascals92** [ToddGreenfield/homebridge-onkyo#143]
**Confirm you have checked the WIKI for troubleshooting first**
_Fill out and check (`[x]`) the boxes which apply.
- Homebridge version: 1.3.8
- Plugin version: latest
- OS, including release name/version: 
- [ ] Homebridge-Onkyo installed via OS/distribution mechanisms
- [ ] You installed using homebridge-config-ui-x
- [x] You enabled homebridge debug output

**Describe the bug**
i can't install the plugin. gui and command the same ..
what about the instructions with "you need GIT" is this a plugin?

**To Reproduce**
Information on your Onkyo receiver:
1. Model information 

Information on your configuration:

Node.js Version  v16.13.0

Npm Version v8.1.0

Information from the log:
USER: root
DIR: /homebridge
CMD: npm install --save homebridge-onkyo@latest

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/untitledlt/eiscp.js.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-29T23_09_21_216Z-debug.log

**Comment by pascals92** [comment]
root@homebridge-vm:/homebridge# apt-get install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.17.1-1ubuntu0.9).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by betamini** [comment]
I am having the same problem. Did you ever find a solution?
