### ISSUE TITLE
3.js fails

### ISSUE THREAD

**Issue by dorian-gray** [ToddGreenfield/homebridge-onkyo#15]
Hi Todd,

When I run 3.js to obtain available commands to add to the config.json I receive the following.

/usr/lib/node_modules/homebridge-onkyo/node_modules/eiscp/examples/3.js: 1: /usr/lib/node_modules/homebridge-onkyo/node_modules/eiscp/examples/3.js: /*jslint: not found
/usr/lib/node_modules/homebridge-onkyo/node_modules/eiscp/examples/3.js: 2: /usr/lib/node_modules/homebridge-onkyo/node_modules/eiscp/examples/3.js: use strict: not found
/usr/lib/node_modules/homebridge-onkyo/node_modules/eiscp/examples/3.js: 3: /usr/lib/node_modules/homebridge-onkyo/node_modules/eiscp/examples/3.js: Syntax error: "(" unexpected
 am by no means a linux expert.  This is on a pi3 running stretch

Any help you can provide will be greatly appreciated.

Thank you!

**Comment by ToddGreenfield** [comment]
Hi. So technically the resulting commands are not added to the config file. The 3.js file in the example folder is just run to output/see what types of commands your recieever is capable of.

How are you running the 3.js file? You should be executing through node, so inside the examples directory run-
"node 3.js" 

Snip from my system-
$ ls -l
total 12
-rw-r--r-- 1 pi pi  463 Mar 10  2018 1.js
-rw-r--r-- 1 pi pi 1416 Mar 10  2018 2.js
-rwxr-xr-x 1 pi pi  407 Mar 10  2018 3.js
$ node 3.js
[ 'system-power',
  'audio-muting',
  'speaker-a',
  'speaker-b',
  'speaker-layout',
  'master-volume',
...

**Comment by dorian-gray** [comment]
Todd,

Worked perfectly that time.  Thank you very much

Ryan Levi
