### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by sgradek-gr** [ToddGreenfield/homebridge-onkyo#16]
Trying to install and getting the below:

C:\WINDOWS\system32>npm install -g homebridge-onkyo
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t git://github.com/tillbaks/node-eiscp.git
npm ERR!
npm ERR! fatal: unable to look up github.com (port 9418) (Either the application has not called WSAStartup, or WSAStartup failed. )
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HTPC\AppData\Roaming\npm-cache\_logs\2018-12-02T21_06_58_438Z-debug.log

**Comment by ToddGreenfield** [comment]
See #3

**Comment by sgradek-gr** [comment]
> See #3

That didn't help. I don't understand.

**Comment by ToddGreenfield** [comment]
Look at the Clised issue #3. It explains how to resolve permission issues which is likely the problem you are having.  Have you been able install any other homebridge plugins?

**Comment by sgradek-gr** [comment]
@ToddGreenfield Yes I have several other plugins installed and working without issue. The onkyo plugin is the only one I cannot install.

**Comment by 400HPMustang** [comment]
@ToddGreenfield so closed issue #3 still doesn't help me. I still have no problem installing other plugins. The instructions all linked in #3 are also Linux instructions and specifically say they don't apply to Windows. Do you have any other suggestions?

**Comment by 400HPMustang** [comment]
Solution for windows is as follows:

Open power shell
Run git config --global url."https://".insteadOf git://
Install plugin as directed.
