### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by scourchesne** [ToddGreenfield/homebridge-onkyo#17]
Any idea why I get this error (running Homebridge in a docker) : 

[2018-12-4 22:59:01] [Stereo] Initializing Onkyo accessory...
module.js:538
throw err;
^

Error: Cannot find module './node_modules/eiscp/eiscp-commands.json'

at Function.Module._resolveFilename (module.js:536:15)
at Function.Module._load (module.js:466:25)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at new HttpStatusAccessory (/root/.homebridge/node_modules/homebridge-onkyo/index.js:84:18)
at Server._loadAccessories (/root/.homebridge/node_modules/homebridge/lib/server.js:297:29)
at Server.run (/root/.homebridge/node_modules/homebridge/lib/server.js:87:38)
at module.exports (/root/.homebridge/node_modules/homebridge/lib/cli.js:45:10)
at Object.<anonymous> (/root/.homebridge/node_modules/homebridge/bin/homebridge:17:22)
_at Module._compile (module.js:635:30)

**Comment by G60GT** [comment]
I have the same problem, despite the mentioned file being where it has to be …

**Comment by ToddGreenfield** [comment]
Take a look at #3 and see if permissions need to be fixed. This is typically the problem.

**Comment by alie2n** [comment]
I have the same problem as the reporter and I just can't wrap my head around this issue.
I have homebridge installed in a docker container and the installation went fine. All files (as far as I can tell) are there and the permissions seem o.k.

How did the reporter of this issue fix it?

**Comment by alie2n** [comment]
Hmm... I don't know if what I did was stupid or not but I got it working for now...
I did:
`docker-compose exec homebridge sh
npm uninstall --unsafe-perm homebridge-onkyo
npm install -g --unsafe-perm homebridge-onkyo`
Now my homebridge starts again and I can see my receiver as a switch.

I fear that by using this method I will loose connectivity as soon as I update the docker image as this change is not within the default config directory...

Any idea how I can contain the changes to within the default node_modules directory /homebridge/node_modules ?

**Comment by ecoen66** [comment]
I had the same issue.  I resolved it by replacing './node_modules/eiscp/eiscp-commands.json' with '/homebridge/node_modules/eiscp/eiscp-commands.json' in the /homebridge/node_modules/homebridge-onkyo/index.js script.

**Comment by djiwondee** [comment]
Hello @ecoen66,

> resolve it by replacing './node_modules/eiscp/eiscp-commands.json' with '/homebridge/node_modules/eiscp/eiscp-commands.json' in the /homebridge/node_modules/homebridge-onkyo/index.js script.

Thanks for pointing me to the right place! It solves really the problem!

**Comment by ToddGreenfield** [comment]
Fixed with latest patch

**Comment by gramtech** [comment]
> I had the same issue. I resolved it by replacing './node_modules/eiscp/eiscp-commands.json' with '/homebridge/node_modules/eiscp/eiscp-commands.json' in the /homebridge/node_modules/homebridge-onkyo/index.js script.

Thanks, this solved the issue for me too.
I've just done an install for first time so is the latest patch available?
