### ISSUE TITLE
Question about nodejs 

### ISSUE THREAD

**Issue by toshibochan** [ToddGreenfield/homebridge-onkyo#170]
The latest update will work with node v14.17.6?

**Comment by cbrandlehner** [comment]
It tested fine with 14.x, 16.x and 18.x

[![Node.js CI](https://github.com/ToddGreenfield/homebridge-onkyo/actions/workflows/nodejs.yml/badge.svg)](https://github.com/ToddGreenfield/homebridge-onkyo/actions/workflows/nodejs.yml)
