### ISSUE TITLE
Dedicated button/element for specific command

### ISSUE THREAD

**Issue by aschmidt74** [ToddGreenfield/homebridge-onkyo#18]
Seems I'm missing out something basic. All I get in Homebridge is an on/off button - that is working fine with my TX-NR905.
How can I switch the HDMI output (sub/main) e.g.?

**Comment by ToddGreenfield** [comment]
Please see the readme for more info. In short, try using an app like EVE instead of the Home app.

**Comment by aschmidt74** [comment]
I've seen https://github.com/ToddGreenfield/homebridge-onkyo/blob/master/README.md and yes, Eve gives some more control (though unreliably). If dummy switches are the key to my question, then how to bind a specific eiscp-command to a switch?

**Comment by Hochiss** [comment]
@aschmidt74 check this:
https://github.com/miracle2k/onkyo-eiscp
this must be what you want ==>  http://midnite.im/de8965
I am studying this also, but if you figured it out please share with us.
