### ISSUE TITLE
iOS 12.2: HomeKit Receiver support

### ISSUE THREAD

**Issue by chris-araman** [ToddGreenfield/homebridge-onkyo#19]
It is looking like iOS 12.2 may soon bring support for Receivers to HomeKit.
https://www.apple.com/ios/home/accessories/

It would be great to bring this support for Onkyo receivers to `homebridge`. I'm happy to try to help contribute to this effort. We have an Onkyo TX-NR787 we can test with.

See this similar work for the new TV support in `homebridge-webos-tv` for LG webOS televisions: https://github.com/merdok/homebridge-webos-tv/issues/87

**Comment by kapps7** [comment]
Interesting so these are the original airplay 2 receivers that were announced at WWDC onwards which at the time seemed like useful as multi room audio only. HomeKit support is awesome. I was just going to comment that inputs on TVs is almost obsolete for anyone with a sound system

**Comment by solowalker27** [comment]
The Receivers section of Apple's HomeKit accessories page is referring to AirPlay 2 integration, allowing the receivers to act as an AirPlay 2 speaker. As far as I know, there won't be a special Receiver profile and I don't think homebridge can add AirPlay 2 to an accessory.

The request for supporting the TV profile is a good one, though, and I second that. With the TV profile, you can control a device's power, volume, input source, and remote control. I'd love for this plugin to convert to the TV profile and I'm considering figuring out how to do that myself.

**Comment by kapps7** [comment]
> The Receivers section of Apple's HomeKit accessories page is referring to AirPlay 2 integration, allowing the receivers to act as an AirPlay 2 speaker. As far as I know, there won't be a special Receiver profile and I don't think homebridge can add AirPlay 2 to an accessory.
> 
> The request for supporting the TV profile is a good one, though, and I second that. With the TV profile, you can control a device's power, volume, input source, and remote control. I'd love for this plugin to convert to the TV profile and I'm considering figuring out how to do that myself.

Airplay 2 integration receivers show up as Speakers not as receivers in the Home app. Although I haven't seen a receiver in the home app yet, I have setup receivers on that list in HomeKit as airplay 2 speakers and they show with the Speaker icon

**Comment by solowalker27** [comment]
Sure, AirPlay 2 speakers show up in Home but I'm pretty certain you can't use something like homebridge to add AirPlay 2 functionality to a device like this. I'd be happy if I was wrong, though.

**Comment by kapps7** [comment]
I am looking at it from the other way ie I'd like what you said 'receiver profile' from a supported airplay 2 receiver so that all the receivers' features can be controlled. Whether a non airplay 2 receiver can be setup this way via home bridge remains to be seen.

**Comment by chris-araman** [comment]
The LG webOS TVs are not (yet) AirPlay 2 enabled, but `homebridge-webos-tv` is capable of making them appear to HomeKit as TV profile accessories. I'm not suggesting we implement AirPlay 2. I'm suggesting we make Onkyo receivers appears to HomeKit as Receiver profile accessories, if such a thing exists (or will soon exist).

**Comment by solowalker27** [comment]
Adopting the TV profile should accomplish what you want.

**Comment by kapps7** [comment]
> Adopting the TV profile should accomplish what you want.

Yep that'll be a great fallback if a receiver profile doesn't eventuate

**Comment by kapps7** [comment]
Intersting on that list, now there is a separate section for Airplay 2 speakers an Airplay 2 receivers. The former lists standalone speakers and the latter are receivers. This list used to be one. Hoping that receivers has dedicated controls

**Comment by toshibochan** [comment]
Big plus+ for improvement Receiver profile accessories

**Comment by solowalker27** [comment]
I forked this and added support for the TV profile. Power, inputs, and remote function (complete with volume up and down support). I don't use zone2 or various other features so I can't verify that I haven't broken anything. Feel free to try it for yourselves. I'll try to be open to fixing issues, and/or submitting a pull request if everything works.

https://github.com/solowalker27/homebridge-onkyo/tree/tv-service

**Comment by chris-araman** [comment]
@solowalker27, thanks for putting this together. Would you want to create a PR for upstream `homebridge-onkyo`?

**Comment by solowalker27** [comment]
I might. The code scrutiny would be good since I don't know node and this is my first contribution to a homebridge plugin. I was hoping others who use some features I don't would test it first, though.

**Comment by chris-araman** [comment]
Trying to install it. Running into the typical permissions issues on Raspbian. Not your issue. Give me some time to work through these and I'll report back.

**Comment by toshibochan** [comment]
This is only for IOS 12.2?
I only was able to install on root on raspberry pi. Hope no need to install on root in the future update.

**Comment by ToddGreenfield** [comment]
Check out issue #3 for help on fixing permissions for failed install. I don't really have time to maintain, but if you all want to do a PR and test, that works for me-

**Comment by chris-araman** [comment]
Fixed my permissions issue and switched to `"accessory": "Onkyo-tv"`.

✅Receiver shows up in iOS 12.2 as a TV.
🚫Input names configured in the Home app on iOS 12.2 are not remembered when Homebridge is restarted.
🚫Can't find a way to get volume working yet. Is this what the `TelevisionSpeaker` is for? Maybe this is just a limitation of the current iOS 12.2 developer beta.
🚫When switching inputs using the remote, I see errors of the form:
> eventInput - ERROR - INVALID INPUT - Model does not support selected input.

I assume this is another `node-eiscp` configuration issue.
🚫Can't hide inputs in the Home app yet, but I suspect that's a limitation of the current iOS 12.2 developer beta.

Is it possible to read the input labels as configured in the receiver via `node-eiscp` in order to avoid repeating them in `config.json` and/or the Home app?

Maybe I need to use something other than `"model": "TX-NR609"`? I would consider updating `node-eiscp` for my TX-NR787, but I think I might need to fork it because it's been archived by @tillbaks. Might be worth a separate effort to fork and update this for more recent models.

Please let me know what I missed.

**Comment by solowalker27** [comment]
Input names not being remembered when changed, I’ve seen others write out the changes to a JSON file and then load them from there if present. I didn’t want to head down that road yet but instead added the ability to specify them in the config file. I’d take a PR for that, otherwise I’ll think about how I’d want to do it.

Volume is controlled via the Remote interface and pressing your device’s physical volume up or down keys. As far as I know, there isn’t another way to do this natively.

The inputs populated initially come from the esicp, I believe from the predefined list of inputs available for the model. As such, I don’t believe it’s actually querying the receiver for the inputs and their labels. You may get different results by specifying a different model in your config. If your model doesn’t have the particular input option, you’ll get that error.

I hadn’t heard of the ability to hide inputs. Not sure how to do that. Have you seen it mentioned in any other plugin that I could take a look at?

**Comment by chris-araman** [comment]
OK, `config.json` is probably fine for persistence, if there's no way to load it from the HomeKit database on launch.

Pressing the volume buttons on my iPad mini 4 running the current iOS 12.2 developer beta, with the Onkyo receiver controls visible doesn't adjust the Onkyo volume. It's only adjusting the device volume. Either HomeKit isn't recognizing that this device supports volume controls, or there's a bug in this iOS 12.2 build.

I think when 12.2 ships, we'll be able hide inputs by unchecking the boxes in the settings UI for a given "TV" accessory in the Home app. I don't think the current betas have this wired up yet, though:
https://github.com/merdok/homebridge-webos-tv/issues/98#issue-403576401

**Comment by solowalker27** [comment]
Let's move the discussion to the PR I created. https://github.com/ToddGreenfield/homebridge-onkyo/pull/21

**Comment by solowalker27** [comment]
I updated the PR. Please take a look at the changes, update your config and plugin and try it out.

**Comment by chris-araman** [comment]
Thanks for your work on this, @solowalker27 and @ToddGreenfield. I've updated my config to use https://github.com/ToddGreenfield/homebride-onkyo#devel.

All of my devices are now running iOS 12.2 or tvOS 12.2.1. It looks like hiding/showing inputs didn't make it into iOS 12.2. Weird that they kept the gray checkmark icons, though. I'm not sure what else those might have been meant to indicate. 🤷🏻‍♂️

✅The TX-NR787 receiver now shows up in the Remote accessible in the iOS Control Center, and the volume controls work there.
✅After moving the Apple TV from the `STRM BOX` input to `PC`—working around a limitation of `node-eiscp`'s TX-NR1000 configuration and lack of TX-NR787 configuration—I was able to configure all of my inputs to appear in the Home app.
✅If I first hit Settings on the physical Onkyo remote, the virtual iOS buttons work: Up, Down, Left, Right, Select/OK, Back.
🚫The other buttons do not seem to work on this remote: Play/Pause, Info. Play/Pause doesn't work when streaming Internet media, and Info doesn't seem to have the same effect as Info or Settings on the physical remote.
🚫My LG webOS TV, configured via https://github.com/merdok/homebridge-webos-tv, no longer appears in the iOS Remote app once the Onkyo Receiver was added. Maybe there is a limit of three devices (two Apple TVs and the receiver)? Or maybe there's an interaction between the TV services implemented by the `Onkyo` platform and the `webostv` accessory?
✅I'm now able to configure HomeKit scenes like "Watch TV" and "Play Xbox". These turn on the LG webOS TV, the Onkyo Receiver, and set the correct inputs. Great progress!

**Comment by solowalker27** [comment]
I can investigate the remote buttons. Then not working until you tap Settings first is… interesting. Not sure what to do about that.  But I can change the buttons to do whatever the receiver supports.

There’s a known issue about multiple remotes not working if they’re behind a single bridge. You can set up another bridge for each TV accessory, or there’s a new option to expose the TVs externally as separate accessories that seems to work. I don’t know how that works yet but we can add it as an option. I’m on my phone but I can find and link to the relevant issue later. 

I’ve been using it a lot, too, and I’ve discovered an interesting issue where Siri won’t control the receiver’s power state, saying it can only do one request at a time. I’m thinking it might be the fact that Power and Mute seem to be attached to the accessory in a way that they’re both On and Off settings. Might need to just remove the Mute option from the main accessory and leave it as an option for the Dimmer volume accessory.

**Comment by solowalker27** [comment]
Here's the issue about multiple remotes.
https://github.com/nfarina/homebridge/issues/2184

I've looked at the code change that adds the ability to expose the TV as an external accessory but don't quite understand how it works so it'll take a bit to figure that out, when I get some time. Theoretically, it might be possible to do the same thing or something similar for multi-zone support.

**Comment by solowalker27** [comment]
K, so it's not Mute that's the extra On/Off. The Mute was already moved to the volume dimmer. I had both the generic `Characteristic.On` and the TV `Characteristic.Active`. We don't need the `Characteristic.On`.

**Comment by toshibochan** [comment]
@solowalker27 how to report issues on your homebridge-onkyo?
https://github.com/solowalker27/homebridge-onkyo

**Comment by solowalker27** [comment]
@toshibochan I enabled Issues on my fork. Didn't realize it wasn't already enabled.

**Comment by toshibochan** [comment]
@solowalker27 thank you enable the issue

**Comment by BenS89** [comment]
Does anyone know when version 0.7 will be released? I´d like to test the iOS 12.2 TV accessory.

**Comment by toshibochan** [comment]
@BenS89 you can instal @solowalker27 version.
sudo npm install -g https://github.com/solowalker27/homebridge-onkyo.git

And update you config file

**Comment by BenS89** [comment]
Works pretty well. It was exactly what I was looking for. Is it also possible to adress spotify connect via an input variable? I would like to have the Spotify app as an input selection within HomeKit. 

Thanks and best regards
