### ISSUE TITLE
Support for airplay

### ISSUE THREAD

**Issue by toshibochan** [ToddGreenfield/homebridge-onkyo#20]
I’m try to set to airplay but not working. Any idea why?

**Comment by cbrandlehner** [comment]
Please provide more information:
At a mimimum, share your configuration used to configure the plugin.

**Comment by toshibochan** [comment]
how to turn on and off Airplay?
I add airplay in the config but no work
"accessories": [
   {
   	"accessory": "Onkyo",
   	"name": "Stereo",
   	"ip_address": "10.0.1.23",
   	"model" : "TX-NR609",
   	"poll_status_interval": "900",
   	"default_input": "airplay",
   	"default_volume": "45",
   	"max_volume": "100",
   	"map_volume_100": true,

**Comment by cbrandlehner** [comment]
This plugin depends on the library https://github.com/tillbaks/node-eiscp which is - unfortunately - no longer maintained and read-only. 'airplay' is not implemented in node-eiscp.

**Comment by toshibochan** [comment]
I wish someone take over node-eiscp and update the file

**Comment by cbrandlehner** [comment]
Have you tried starting homebridge with debug turned on? The log will display something like the following. Check if any input may relate to airplay.
```
[2/28/2020, 9:00:24 AM] [Onkyo] Creating TV service for receiver Receiver
[2/28/2020, 9:00:24 AM] [Onkyo] [ { code: '10', label: 'dvd' },
  { code: '23', label: 'cd' },
  { code: '24', label: 'fm' },
  { code: '25', label: 'am' },
  { code: '26', label: 'tuner' },
  { code: '27', label: 'music-server' },
  { code: '28', label: 'internet-radio' },
  { code: '29', label: 'usb' },
  { code: '40', label: 'universal-port' },
  { code: '00', label: 'video1' },
  { code: '01', label: 'video2' },
  { code: '02', label: 'video3' },
  { code: '03', label: 'video4' },
  { code: '05', label: 'video6' },
  { code: '2B', label: 'network' },
  { code: '2C', label: 'usb' } ]

```
