### ISSUE TITLE
homebridge on docker can't find module './node_modules/eiscp/eiscp-commands.json'

### ISSUE THREAD

**Issue by djiwondee** [ToddGreenfield/homebridge-onkyo#22]
I'm running homebridge on Docker and tried to install homebridge-onky plugin. Installation is successful using homebridge web interface

![image](https://user-images.githubusercontent.com/37173958/55289470-7818cf80-53c7-11e9-8e13-79c6464a72f2.png)

But a restart of homebridge raises an error:

![image](https://user-images.githubusercontent.com/37173958/55289482-a39bba00-53c7-11e9-9a30-753f97e7d925.png)

But the module is there:

![image](https://user-images.githubusercontent.com/37173958/55289512-0d1bc880-53c8-11e9-896d-3b74cfcbd342.png)

Any idea what I made wrong?

**Comment by ecoen66** [comment]
I have the same issue.

**Comment by djiwondee** [comment]
Problem solved: see above!

**Comment by cbrandlehner** [comment]
Not reproducing - issue should be closed

**Comment by cbrandlehner** [comment]
I upgraded homebridge to the 0.4.50 build of https://github.com/oznu/docker-homebridge and not the problem reoccurs for me, asking for the eiscp file in the path before the last fix.
I will submit a patch to fix this.

**Comment by cbrandlehner** [comment]
I commited the changes. @ToddGreenfield please push to npm.

**Comment by Hochiss** [comment]
the error persists still  at 0.6.5.
cf. above solution,  edit /homebridge/node_modules/homebridge-onkyo/index.js:
 from: 
    var eiscpData = require('../eiscp/eiscp-commands.json');
to :
   var eiscpData = require('./node_modules/eiscp/eiscp-commands.json');

**Comment by cbrandlehner** [comment]
The current version on Github is 0.6.6 - waiting for @ToddGreenfield to publish this version to npmjs.org as I do not have the access rights to do so.

**Comment by ToddGreenfield** [comment]
Christian- I am not able to maintain this anymore. If you would like to be a maintainer on npm let me know your username and I can grant access to update.

**Comment by toshibochan** [comment]
@solowalker27 homebridge-onkyo can be add in HomeKit 

https://github.com/solowalker27/homebridge-onkyo

**Comment by cbrandlehner** [comment]
New version was published on GitHub and on npmjs.org
