### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by jhuebsch** [ToddGreenfield/homebridge-onkyo#3]
It appears that the github.com/tillbaks/node-eiscp.git repo no longer exists

Log message below:
`fetchPackageMetaData error for eiscp@git://github.com/tillbaks/node-eiscp.git Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/tillbaks/node-eisc`

**Comment by ToddGreenfield** [comment]
It is still out there. What version of npm are you at?

**Comment by jhuebsch** [comment]
After a whole bunch of research and back and forth, I think this boils back to me being an ignorant npm newbie and running the install command via sudo or as root. Let this be a lesson for all other newbies.

Sorry for the non-issue and thanks for the prompt response.

**Comment by ToddGreenfield** [comment]
@jhuebsch No worries! We were all newbies at one point.

**Comment by anarchydude** [comment]
Here's some additional information for others that helped me resolve the similar permissions issues.

From here: https://github.com/KraigM/homebridge-harmonyhub/issues/97

> I actually managed to solve it by using Option 1 from this page:
> https://docs.npmjs.com/getting-started/fixing-npm-permissions
> 
> Find the path to npm's directory:
> npm config get prefix
> For many systems, this will be /usr/local.
> WARNING: If the displayed path is just /usr, switch to Option 2 or you will mess up your permissions.
> Change the owner of npm's directories to the name of the current user (your username!):
> sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
> This changes the permissions of the sub-folders used by npm and some other tools (lib/node_modules, bin, and share).

I had usr/local in my case, so I just ran the chown command. The plugin installs correctly now. I did also install nvm just in case I need that down the line.

**Comment by tkundhi** [comment]
Hi guys, I'm having install issues also and like @jhuebsch I'm a newbie, both with npm and also raspberrypi. I've reinstalled NPM using NVM (option 1 from fixing permissions link) but continue to have issues. 

I'm running on a pi3, with jessie. Originally installed homebridge via pi user and then changed things to autostart as a service under the homebridge user. Primarily I use the graphical UI (homebridge-config-ui-x v2.6.0) but have also tried installing via command line. All my plugins are currently under /usr/lib/homebridge. My npm prefix /usr

When I try to install I get an error that says: Please try running this command again as root/Administrator

If I try to install as root I get the following in the log file.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-onkyo' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 4bff9300c1ed38ab
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-onkyo 550ms (from cache)
8 silly pacote tag manifest for homebridge-onkyo@latest fetched in 672ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-onkyo@0.6.2 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/math-round 150ms (from cache)
15 silly pacote range manifest for math-round@^1.0.0 fetched in 160ms
16 silly resolveWithNewModule math-round@1.0.0 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/polling-to-event 278ms (from cache)
18 silly pacote range manifest for polling-to-event@^2.0.2 fetched in 293ms
19 silly resolveWithNewModule polling-to-event@2.1.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/request 304ms (from cache)
21 silly pacote range manifest for request@^2.69.0 fetched in 334ms
22 silly resolveWithNewModule request@2.83.0 checking installable status
23 silly fetchPackageMetaData error for eiscp@git://github.com/tillbaks/node-eiscp.git Command failed: /usr/bin/git clone -q git://github.com/tillbaks/node-eiscp.git /root/.npm/_cacache/tmp/git-clone-8a13db4e
23 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-8a13db4e': Permission denied
24 verbose stack Error: Command failed: /usr/bin/git clone -q git://github.com/tillbaks/node-eiscp.git /root/.npm/_cacache/tmp/git-clone-8a13db4e
24 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-8a13db4e': Permission denied
24 verbose stack
24 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
24 verbose stack     at emitTwo (events.js:126:13)
24 verbose stack     at ChildProcess.emit (events.js:214:7)
24 verbose stack     at maybeClose (internal/child_process.js:925:16)
24 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
25 verbose cwd /home/pi
26 verbose Linux 4.9.59-v7+
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-onkyo"
28 verbose node v8.9.4
29 verbose npm  v5.6.0
30 error code 128
31 error Command failed: /usr/bin/git clone -q git://github.com/tillbaks/node-eiscp.git /root/.npm/_cacache/tmp/git-clone-8a13db4e
31 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-8a13db4e': Permission denied
32 verbose exit [ 1, true ]

I don't want to hand ownership of the /usr directory as I believe that will create other potential issues in the future.

If necessary, I'm willing to start from scratch and reinstall everything but if I do that I want to be certain I do repeat my same mistake.

Any help is much appreciated.

**Comment by tkundhi** [comment]
OK, update. I got the plugin to install but my permission are not right. I had to run the install as root, in the /root folder and issue the following command. Without sudo it would not install. I'm definitely confused.

root@raspberrypi:~# sudo npm install -g homebridge-onkyo

**Comment by ToddGreenfield** [comment]
Try using option 2 from the link referenced. https://docs.npmjs.com/getting-started/fixing-npm-permissions 
Then you would need to uninstall all references of the plugin (or other plugins as well), and reinstall using 
npm install -g plugin-name
It should install into the new npm global directory.

**Comment by tkundhi** [comment]
@ToddGreenfield thanks for the reply. Actually Option 2 is what I had done. Sorry I had a typo my previous comment. 

Something off with my install as I could not locate the node_modules/eiscp/eiscp-commands.yaml file after the plugin install. The eiscp folder is there and contains other files. 

I think I'll bite the bullet and reinstall everything from scratch and install npm via nvm before installing homebridge.

**Comment by ToddGreenfield** [comment]
I don’t believe the yaml file is there as it is in another repo/fork of eiscp, I just have not updated the readme yet.

**Comment by tkundhi** [comment]
@ToddGreenfield OK thx.
