### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by bkonijn** [ToddGreenfield/homebridge-onkyo#30]
Hi, I cannot install the plugin (not 0.7.0 nor 0.6.5). "This is related to npm not being able to find a file." Am I doing something wrong?

**Comment by bkonijn** [comment]
pi@raspberrypi:~/.homebridge $ sudo npm install -g homebridge-onkyo
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/tillbaks/node-eiscp.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-28T10_48_51_239Z-debug.log

**Comment by bkonijn** [comment]
sudo npm install -g git+https://git@github.com/solowalker27/homebridge-onkyo.git
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://git@github.com/solowalker27/homebridge-onkyo.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-28T10_51_26_731Z-debug.log

**Comment by bkonijn** [comment]
solved. I had to install git, and run the installation of the plugin as root (sudo -i)

**Comment by cbrandlehner** [comment]
Thanks for letting us know and good to see you already solved the issue.
