### ISSUE TITLE
Audio Control

### ISSUE THREAD

**Issue by MiranoV** [ToddGreenfield/homebridge-onkyo#32]
i've got the TX-NR509 and i would love to control the sound from my apple homekit. is this possible? current config:

        {
            "name": "Receiver Onkyo",
            "ip_address": "192.168.2.1",
            "model": "TX-NR509",
            "poll_status_interval": "900",
            "default_input": "net",
            "default_volume": "10",
            "max_volume": "50",
            "map_volume_100": true,
            "zone": "main",
            "accessory": "Onkyo"
        }

Also, where can i find the default_input list?

**Comment by cbrandlehner** [comment]
Default Input is what is deplayed on your Onkyo. It can be: TV, Game, net, ...

This is the full list, however keep in mind that not every Onkyo model is equipped with all features:

```
  'dvd',
  'bd',
  'tape-1',
  'tv',
  'tape',
  'tape2',
  'phono',
  'cd',
  'fm',
  'am',
  'tuner',
  'music-server',
  'p4s',
  'dlna',
  'internet-radio',
  'iradio-favorite',
  'usb',
  'multi-ch',
  'xm',
  'sirius',
  'universal-port',
  'video1',
  'vcr',
  'dvr',
  'video2',
  'cbl',
  'sat',
  'video3',
  'game',
  'video4',
  'aux1',
  'video5',
  'aux2',
  'video6',
  'pc',
  'video7',
  '07',
  '08',
  '09',
  'network',
  'net',
  'up',
  'down',
  'query'
```

**Comment by toshibochan** [comment]
Anyone was able to do Airplay input?

**Comment by cbrandlehner** [comment]
There is already an issue documented on Airplay. Closing this one.
