### ISSUE TITLE
config.json: inputs/switches/commands

### ISSUE THREAD

**Issue by Hochiss** [ToddGreenfield/homebridge-onkyo#33]
Thanks for this great plugin!
Now  I can ON/OFF my Onkyo NR636, but would you please tell how to select inputs, or the generic settings with inputs/switches/commands in config.json into e.g. wiki? 

the initial [config](https://github.com/ToddGreenfield/homebridge-onkyo) as accessories works, but for what reason it cannot reflect the correct status on/off in HomeKit like [Samsung  TV](https://github.com/tavicu/homebridge-samsung-tizen) or my [TP-link plug](https://midnite.im/de8965)(which controls the Onkyo  and TV, etc.) , at moment if I off TV, Onkyo will also off, which is also logical and correct by means of HDMI CEC. 

@toshibochan: I tried [your config as platform "onkyo"](https://github.com/ToddGreenfield/homebridge-onkyo/issues/22#issuecomment-520579198), but error shows the platform is not recognized. Have you remove the accessories section for onkyo?  could you elaborate a little more? 

BTW: This is what I would like to reach:
https://midnite.im/de8965

**Comment by toshibochan** [comment]
Did you install @solowalker27 homebridge-onkyo?

**Comment by toshibochan** [comment]
@solowalker27 is platform not accessories

**Comment by Hochiss** [comment]
@toshibochan thanks for sharing! 
Do you mean Tod's plugin don't have these options of platform? vs. @solowalker27?

**Comment by solowalker27** [comment]
Correct. I forked Todd’s plugin to contribute some new features including building our platform support. As that’s a major breaking change, I haven’t merged it to Todd’s yet. Still unsure as to when that would be a good idea. Perhaps we should just rip the bandaid off. 

I’m currently trying to solve a couple bugs for iOS 13, though. When I get those fixed I might be more inclined to get a PR going.

**Comment by Hochiss** [comment]
@solowalker27 thanks for passing by.
I don't know if I should further discuss here or in your board. But I think  your "platform" is absolutely  a great idea & break change! Merge your with Todd's is likely to give wings to fly.
