### ISSUE TITLE
Input list on

### ISSUE THREAD

**Issue by zany92** [ToddGreenfield/homebridge-onkyo#37]
Hi,

First of all, this homebridge plugin is a master piece, congrats to the team. I was looking for this since a very long time.

I used Eve slider to find the input values I need on my TX-NR656 (I set TX-NR609 as my onkyo model is not listed). I can find AM, Aux, Bluetooth, CBL, CD,DVD, FM, multiple input Net, Net USB, input PC but I can't find STRM BOX.

Any advice on what to do please?
--

**Comment by ripper64** [comment]
I have the same model and I am experiencing the same problem.

**Comment by cbrandlehner** [comment]
@zany92 and @ripper64 please start homebridge in debug mode and look for these lines in the log:
```
[2/28/2020, 9:00:24 AM] [Onkyo] Creating TV service for receiver Receiver
[2/28/2020, 9:00:24 AM] [Onkyo] [ { code: '10', label: 'dvd' },
  { code: '23', label: 'cd' },
  { code: '24', label: 'fm' },
  { code: '25', label: 'am' },
  { code: '26', label: 'tuner' },
  { code: '27', label: 'music-server' },
  { code: '28', label: 'internet-radio' },
  { code: '29', label: 'usb' },
  { code: '40', label: 'universal-port' },
  { code: '00', label: 'video1' },
  { code: '01', label: 'video2' },
  { code: '02', label: 'video3' },
  { code: '03', label: 'video4' },
  { code: '05', label: 'video6' },
  { code: '2B', label: 'network' },
  { code: '2C', label: 'usb' } ]

```

**Comment by cbrandlehner** [comment]
@zany92 @ripper64 
I had a look into EISCP (which is not part of this project, we just load that dependency) and it seems not to support STRM BOX.
Unfortunately the EISCP library we are using is no longer being maintained. It would need somebody to take over and create a new fork of it to support newer devices.
Look here: https://github.com/tillbaks/node-eiscp

I am also marking this as enhancement and will close the issue.

**Comment by ripper64** [comment]
Thanks for the update. I was able to run hoobs in debug mode and this is from the logs for my TX-NR656 model. 

[
  { code: '10', label: 'dvd' },
  { code: '23', label: 'cd' },
  { code: '24', label: 'fm' },
  { code: '25', label: 'am' },
  { code: '26', label: 'tuner' },
  { code: '27', label: 'music-server' },
  { code: '28', label: 'internet-radio' },
  { code: '29', label: 'usb' },
  { code: '40', label: 'universal-port' },
  { code: '00', label: 'video1' },
  { code: '01', label: 'video2' },
  { code: '02', label: 'video3' },
  { code: '03', label: 'video4' },
  { code: '05', label: 'video6' },
  { code: '2B', label: 'network' },
  { code: '2C', label: 'usb' }
]
