### ISSUE TITLE
Input selector maybe broke?

### ISSUE THREAD

**Issue by wangel** [ToddGreenfield/homebridge-onkyo#44]
Upgraded the plugin today.  I removed my old config and added the following config;
`  "name": "Onkyo",
            "receivers": [
                {
                    "name": "Stereo",
                    "model": "TX-NR609",
                    "ip_address": "172.16.1.120",
                    "default_input": "DVD",
                    "default_volume": "20",
                    "max_volume": "55",
                    "poll_status_interval": "0",
                    "map_volume_100": true,
                    "volume_dimmer": false,
                    "switch_service": false,
                    "filter_inputs": true,
                    "inputs": [
                        {
                            "input_name": "DVD",
                            "display_name": "NFX"
                        },
                        {
                            "input_name": "SAT",
                            "display_name": "TV"
                        },
                        {
                            "input_name": "NET",
                            "display_name": "NET"
                        },
                        {
                            "input_name": "GAME",
                            "display_name": "GAME"
                        }
                    ]
                }
            ],
            "platform": "Onkyo"`

Everything seems to work, however the input selector is blank in the home app, and it was blank on my ipad.  It's also blank on the watch app.

I have a TX-626, configured as a TX-609.  I tried a couple of other models listed in the file, no luck.

I also see this error;
`HAP Warning: Characteristic 0000011A-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000D8-0000-1000-8000-0026BB765291. Adding anyway.`

I'm not sure if that's related to Onkyo or another device.

I'd also like to add, that the receiver no longer shows in the EVE app....

**Comment by iondarie** [comment]
Having the same issue no thing shows up in the input selector.

**Comment by Staphylococcus** [comment]
Same issue, not sure how to proceed.

**Comment by thechris1992** [comment]
+1 and same with the eve app

**Comment by solowalker27** [comment]
First of all, Apple hasn't yet allowed third party apps to see and interact with TVs. Now that this plugin is a TV accessory, it won't appear in Eve or any other third party app.

As for your inputs being empty, your inputs are not properly defined. You have them as:

`"inputs": [
				{
					"input_name": "DVD",
					"display_name": "NFX"
				},
				{
					"input_name": "SAT",
					"display_name": "TV"
				},
				{
					"input_name": "NET",
					"display_name": "NET"
				},
				{
					"input_name": "GAME",
					"display_name": "GAME"
				}
			]`

If you look at the README.md, there's an example config snippet in there that shows how they're supposed to be formatted. But it'd be like this:

`"inputs": {
				"DVD": "NFX",
				"SAT": "TV",
				"NET": "NET",
				"GAME": "GAME"
			}`

Lastly, it doesn't really matter but `"name": "Onkyo"` isn't necessary anymore.

**Comment by solowalker27** [comment]
I stand corrected a bit. Looks like when my changes were merged, some things weren't the same as when I originally wrote them. I'll try to take a look at what might be the problem but I'm less familiar with the code now.

**Comment by solowalker27** [comment]
Actually, looks like @cbrandlehner made some significant changes to the plugin recently. I was hoping to be able to quickly jump in and help y'all but I don't have the bandwidth to come up to speed on his changes. Hopefully he'll have time soon to take a look.

**Comment by cbrandlehner** [comment]
@solowalker27 true, I made some changes to the configuration as the config format was not compatible with homebridge-config-ui-x which relies on a proper config.schema.json file.
I had some problems reading the new config and adapt it to your code, but I think this should be fine now.
Can you please have a look and advise?
