### ISSUE TITLE
Plugin won't install

### ISSUE THREAD

**Issue by mark125431** [ToddGreenfield/homebridge-onkyo#46]
Hi 

Every time i try to install this plugin i get the below errors :(  Any help would be much appreciated.

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/tillbaks/node-eiscp.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by solowalker27** [comment]
Can you share the command you’re using to try to install?

**Comment by mark125431** [comment]
Hi

I’m using HOOBS and searching for the plugin and then pressing install.

I have also tried the below command from the terminal screen in HOOBS 

Sudo npm install -g homebridge-onkyo

**Comment by cbrandlehner** [comment]
@mark125431  
Although request was listed as a dependency in package.json, the code does not use the request library.
I am going to remove this.

**Comment by mark125431** [comment]
Thanks @cbrandlehner 

I’ve just run it again but still get the below errors. 😢 any help would be amazing 

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t git://github.com/tillbaks/node-eiscp.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by cbrandlehner** [comment]
try installing "**git**" on your platform.
Depending on OS it might be by using
```
apt-get install git
yum install git
```
or similar.

**Comment by mark125431** [comment]
Perfect.  Thanks
All installed now.  However it isn’t picking up the “TV”. Input.  Any ideas ?
I have it set as model TX-NR609. But my unit is a pioneer vsx-831 using the onkyo protocol

**Comment by cbrandlehner** [comment]
Please open a new issue and close this one. :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
