### ISSUE TITLE
Tv input not working

### ISSUE THREAD

**Issue by mark125431** [ToddGreenfield/homebridge-onkyo#63]
Hi @cbrandlehner 

My receiver is recognised by the plugin and almost everything works as expected however  it isn’t picking up the “TV”. Input. Any ideas ?
I have it set as model TX-NR609 in the plugin settings.
My audio unit is a pioneer vsx-831 using the onkyo protocol.

Regards Mark

**Comment by cbrandlehner** [comment]
Sorry, no idea on that. Was not me who wrote that part of the code.

**Comment by mark125431** [comment]
Anyone else have an idea of what to try please?

**Comment by mark125431** [comment]
Anyone pls ,?

**Comment by solowalker27** [comment]
I'd recommend trying another model instead of TX-NR609. Your VSX-831 is 5 years newer than the NR609 and things could be different. Perhaps try an Onkyo model from the same year, which looks like 2016. Maybe TX-NR656? I'm not sure if the currently released version of this package supports that model but my PR https://github.com/ToddGreenfield/homebridge-onkyo/pull/80 does. You could test that PR or wait until it's merged.

**Comment by mark125431** [comment]
Thanks for you help @solowalker27 ,
What you’ve said makes sense however it doesn’t look like TX-NR656 is supported by this plugin,  I’ll do a search for a few of the other models to see if they will work

**Comment by solowalker27** [comment]
Like I said, the currently released version doesn’t support the 656 but my pull request does. You can install the branch or wait for it to be merged and released into this plugin. Not sure when that will happen, though.

**Comment by DeanPix** [comment]
I am also waiting for the support of the NR656 model. There is still a chance for this?

**Comment by solowalker27** [comment]
My branch with the updated model list was already merged and released. This should be resolved.

**Comment by solowalker27** [comment]
Since this issue is stale and should/could have been resolved with an update, I'm closing this. If it's still a problem, reopen (or file a issue) and give updated details describing the problem and what version of the plug-in you're currently using.
