### ISSUE TITLE
install npm code 128

### ISSUE THREAD

**Issue by leglagladu13** [ToddGreenfield/homebridge-onkyo#64]
Hello, when i want to install the beautiful homebridge-onkyo i have a error npm see below :

> pi@casarasp:~ $ sudo npm i -g homebridge-onkyo
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/tillbaks/node-eiscp.git /root/.npm/_cacache/tmp/git-clone-e1cea99f/.git
npm ERR! fatal: impossible de créer les répertoires de premier niveau dans '/root/.npm/_cacache/tmp/git-clone-e1cea99f/.git'
npm ERR! 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-02T10_16_08_511Z-debug.log`

Can you help me please, Thank you node v10.15.2 and npm v6.14.1

![Capture d’écran 2020-03-02 à 10 51 59](https://user-images.githubusercontent.com/32463773/75668362-8592a580-5c79-11ea-9166-0611ea1d3bea.png)

**Comment by cbrandlehner** [comment]
please reopen if problem persists with #65

**Comment by leglagladu13** [comment]
I have the same issue 
![Capture d’écran 2020-03-03 à 12 40 04](https://user-images.githubusercontent.com/32463773/75772724-c6a7ba00-5d4c-11ea-81b6-f4e59832e22d.png)
