### ISSUE TITLE
Code 128 npm

### ISSUE THREAD

**Issue by leglagladu13** [ToddGreenfield/homebridge-onkyo#66]
It's the same issue with 0.7.17 #64 
![Capture d’écran 2020-03-03 à 12 40 04](https://user-images.githubusercontent.com/32463773/75773849-fc4da280-5d4e-11ea-88f8-8969ff979a28.png)

**Comment by cbrandlehner** [comment]
Can anybody reproduce and give me a hint. It does not reproduce for me nor for automated GitHub continuous integration check.
I have no clue what's going on.

**Comment by leglagladu13** [comment]
https://github.com/nfarina/homebridge/issues/1661 I find a issue thanks for your help and your fast reply :), this method works but it's very not conventional
