### ISSUE TITLE
This works for my Pioneer SX-S30 receiver, but I can't get the inputs to align

### ISSUE THREAD

**Issue by stevesanda** [ToddGreenfield/homebridge-onkyo#67]
**Describe the bug**
I am trying to figure out how to get a list of inputs for my Pioneer receiver, which happens to use the same protocol as Onkyo receivers. Once I have this, I would be able to add "STREAMBOX" (for example) to inputs so that it shows up and can be controlled by HomeKit.

**To Reproduce**
Information on your Onkyo receiver:
1. Model information - Pioneer SX-S30

Information on your configuration:
1. Homebridge config

`{
        "platform": "Onkyo",
        "receivers": [
                {
                "model": "TX-NR609",
                "ip_address": "10.0.1.85",
                "poll_status_interval": "3000",
                "name": "Roundhouse AVR",
                "volume_dimmer": true,
                "map_volume": true,
                "filter_inputs": true,
                "inputs": [
                        {
                                "input_name": "network",
                                "display_name": "Network"
                        },
                        {
                                "input_name": "streambox",
                                "display_name": "Apple TV"
                        }
                ]
                }
        ]
    },`

Information from the log:
1. Homebridge log file showing relevant information. Experienced users are asked to turn debug on.

`Mar 03 20:45:33 HOMEBRIDGE homebridge[4343]: [3/3/2020, 8:45:33 PM] [Onkyo] Event - System Power changed: on
Mar 03 20:45:33 HOMEBRIDGE homebridge[4343]: [3/3/2020, 8:45:33 PM] [Onkyo] eventInput - ERROR - INVALID INPUT - Model does not support selected input.
`

**Comment by cbrandlehner** [comment]
@stevesanda 
Please read this information in the WIKI and provide the DEBUG information that lists all available inputs when starting the plugin.
https://github.com/ToddGreenfield/homebridge-onkyo/wiki
