### ISSUE TITLE
unable to install plugin with homebridge docker environment

### ISSUE THREAD

**Issue by Goldsucher** [ToddGreenfield/homebridge-onkyo#69]
get this error when I try to install the plugin through homebridge UI:

`USER: root`
`DIR: /homebridge`
`CMD: npm install --save homebridge-onkyo@latest`

`npm ERR! code 1`
`npm ERR! Command failed: git clone --mirror -q git://github.com/tillbaks/node-eiscp.git` `/root/.npm/_cacache/tmp/git-clone-beacf4cb/.git`
`npm ERR! /root/.npm/_cacache/tmp/git-clone-beacf4cb/.git: Permission denied`
`npm ERR! `

`npm ERR! A complete log of this run can be found in:`
`npm ERR!     /root/.npm/_logs/2020-03-07T12_28_35_357Z-debug.log`

`Command failed. Please review log for details.`

Homebridge is running in a docker container on Synology DS216+

**Comment by cbrandlehner** [comment]
@Goldsucher 
This is a permission problem in the file system and not related to this plugin.
Please check the troubleshooting information of homebridge.
