### ISSUE TITLE
Support for RZ models 

### ISSUE THREAD

**Issue by VanillaXtract** [ToddGreenfield/homebridge-onkyo#7]
I’m fairly new to homebridge and automations. I have this setup using the default model. My receiver is a TX-RZ810. When I connect to it via the eve app, the input selection is very flaky. Is there a better model to select or something I can do to improve compatibility?

**Comment by ToddGreenfield** [comment]
Hi. Yes, the input selection is flaky. I could not think of a better way to implement it as Homekit doesn't have input functionality. To my knowledge, I don't think it will help much to switch to another model. What has worked best is to do the following:
1. Use an app like Onkyo Remote3 and change to the preferred input (example: Net).
2. Use the Eve app, create a scene called Network. It should already be on the right number from step 1.
3. Tell Siri to "set Network"
Do this for each-

If you are up for tinkering, I did see in the yaml file at (https://github.com/miracle2k/onkyo-eiscp) that the RZ810 is supported, however this plugin's dependent library (https://github.com/tillbaks/node-eiscp) eiscp-commands.json isn't up to date with the yaml file in onkyo-eiscp. You could try updating the json file as per the instructions at the bottom of tillbaks page and then change your model# in the config.json and see if that helps. The functionality will still be flaky though.

I literally just changed/reduced the logging output on this plugin so not much will show via logging unless debug is used now. Too much was dumping to the syslog-

**Comment by VanillaXtract** [comment]
I will try playing with that stuff. I mainly switch between my kodi box and DirecTV, both on HDMI inputs. When I switch and check Eve, it shows the same for both.
Input Label "SET ERROR"
Input Source 0
Volume 30%

**Comment by VanillaXtract** [comment]
Any updates? I have not been able to update the file myself.

**Comment by ToddGreenfield** [comment]
Not something I have had a chance to look at.

**Comment by cbrandlehner** [comment]
stale
