### ISSUE TITLE
Merge back fork (ToddGreenfield & SoloWalker) projects into ToddGreenfield as looks like Todd is now actively maintaining original codebase (will cross post)

### ISSUE THREAD

**Issue by taw123** [ToddGreenfield/homebridge-onkyo#70]
**Is your feature request related to a problem? Please describe.**
Thanks for all your work on this. I moved to SoloWalker's plugin given issue with the Todd Greenfield's plugin on my Onkyo and to gain support for Platform. 

Looks like Todd is now actively mantaining his original plugin that was forks (though seems he implemented the Platform definition slightly differently).

Request to have all changes made in SoloWalker fork integrated into the mainline codebase this unifying the root. This will allow SoloWalker to continue if he wishes to in the future push out any updates and if not at least the work done will not be lost and those of us who have been using and testing it can switch over to Todd's plug in with minimal disruption (at the moment since he published privately I unfortunately still see Todd's plugin as my installed plugin with he most recent update now as an available update via HomeBridgeUI/NPM.

Thanks both for all the great work! And as a former Apple Engineer please let me know if there is anything I can do to help.

Regards,
Tom

**Comment by taw123** [comment]
https://github.com/solowalker27/homebridge-onkyo/issues/13

**Comment by cbrandlehner** [comment]
Looks like we are in kinda deadlock situation. Some developers, no lead, no plan.

**Comment by jondthompson** [comment]
I believe @cbrandlehner is the lead at this point. Can we wrap up anything left to be done with this issue and close it?

**Comment by cbrandlehner** [comment]
What about creating a new plugin (based on current code) on github and npm and archive this fork?

**Comment by solowalker27** [comment]
My code was merged back into the main branch. That should be enough to close this.

There already is a new plugin someone created homebridge-onkyo-pioneer. I tried it out for a month or two. It's still pretty rough. Perhaps eventually it will be stable enough to just deprecate this one entirely, but IMO it's not there yet.
