### ISSUE TITLE
Please add support for Onkyo TX-NR686 (and all in series)

### ISSUE THREAD

**Issue by alexsalex** [ToddGreenfield/homebridge-onkyo#72]
Subj))) Please!

**Comment by solowalker27** [comment]
My PR https://github.com/ToddGreenfield/homebridge-onkyo/pull/80 includes an updated eiscp.js that I found which supports up to the series including TX-NR676, which is much much closer to your TX-NR686. I'd recommend trying the 676 to see if it works for you. You can test the PR or wait until it's merged.

**Comment by alexsalex** [comment]
Looks like it works, but the issues is the same....

**Comment by solowalker27** [comment]
What's the problem? What issues are you seeing? Did you tell it your receiver was a TX-NR676 and it didn't function properly or did it throw any errors? Can you provide a log?

**Comment by alexsalex** [comment]
https://github.com/ToddGreenfield/homebridge-onkyo/issues/71

yes, I did update it to 0.8.0. Checking the solution which was provided in the topic #71

**Comment by jondthompson** [comment]
With my TX-NR686, I'm seeing erroneous inputs, and have no idea how to work within the "net" input, which is where they throw all of the digital network inputs (Spotify, airplay, etc..)

**Comment by cloudkucooland** [comment]
I've spent a fair bit of time building an EISCP library in Go, and working on my own bridge software. I have a TX-NR686. The net input is its own beast. It simply cannot work like the "normal" sources. I have basically the same functionality  in my bridge that this plugin provides. 

I'm still working on getting listening modes and other things working.

![Screen Shot 2021-02-04 at 11 08 52 AM](https://user-images.githubusercontent.com/8037678/106929065-84fc5d80-66d9-11eb-9c4e-2ca6fdc4d13d.png)

**Comment by solowalker27** [comment]
Since this issue is stale and should/could have been resolved with an update, I'm closing this. If it's still a problem, reopen (or file a issue) and give updated details describing the problem and what version of the plug-in you're currently using.
