### ISSUE TITLE
Invalid Input Error

### ISSUE THREAD

**Issue by ripper64** [ToddGreenfield/homebridge-onkyo#74]
**Confirm you have checked the WIKI for troubleshooting first**
_Fill out and check (`[x]`) the boxes which apply.
- Hoobs version: 3.1.23
- Homebridge version: 0.4.50
- Plugin version: 0.7.17
- Node Version: 12.14.1
- OS, including release name/version: 
- [ ] Homebridge-Onkyo installed via OS/distribution mechanisms
- [ ] You installed using homebridge-config-ui-x
- [X] You enabled homebridge debug output

**Describe the bug**
When my TX-NR656 receiver is set to tv input the following error is displayed.

[Homebridge] [4/5/2020, 5:41:25 PM] [Onkyo] eventInput - ERROR - INVALID INPUT - Model does not support selected input.

**To Reproduce**
Information on your Onkyo receiver:
1. Model information

TX-NR656

Information on your configuration:
1. Homebridge config

    {
        "model": "TX-NR609",
        "ip_address": "192.168.1.200",
        "poll_status_interval": "3000",
        "name": "Receiver",
        "zone": "main",
        "default_volume": "50",
        "max_volume": "83",
        "map_volume_100": false,
        "volume_dimmer": false,
        "switch_service": false,
        "filter_inputs": true
    }

Information from the log:
1. Homebridge log file showing relevant information. Experienced users are asked to turn debug on.
Hint: The more information you provide here, the easier it is to help you. Do NOT provide only a single line showing an error message - give the develpers a chance by providing a full log.

**Expected behavior**

I would like to be able to select the TV input via HomeKit. 

**Screenshots**

**Additional context**

**Comment by solowalker27** [comment]
Since this issue is stale and should/could have been resolved with an update, I'm closing this. If it's still a problem, reopen (or file a issue) and give updated details describing the problem and what version of the plug-in you're currently using.
