### ISSUE TITLE
Can't use TX-NR676

### ISSUE THREAD

**Issue by rosorrentino** [ToddGreenfield/homebridge-onkyo#75]
**Confirm you have checked the WIKI for troubleshooting first**
_Fill out and check (`[x]`) the boxes which apply.
- Homebridge version:
1.0.4
- Plugin version:
0.7.17
- OS, including release name/version: 
- [ ] Homebridge-Onkyo installed via OS/distribution mechanisms
- [X] You installed using homebridge-config-ui-x
- [ ] You enabled homebridge debug output

**Describe the bug**
When I try to add the model 'TX-NR676' the plugin fails to load, if I try 609 works, but them it don't support the same inputs 

**To Reproduce**
Information on your Onkyo receiver:
1. Model information
TX-NR676
Information on your configuration:
1. Homebridge config
{
"platforms": [
	{
	"platform": "Onkyo",
	"map_volume_100": false,
	"volume_dimmer": false,
	"switch_service": false,
	"filter_inputs": true,
	"receivers": [{
		"model": "TX-NR676",
		"ip_address": "192.168.1.60",
		"poll_status_interval": "3000",
		"name": "Receiver",
		"zone": "main",
		"default_input": "video4",
		"default_volume": "10",
		"max_volume": "40",
		"inputs": [{
				"input_name": "TV",
				"display_name": "TV"
			},
			{
				"input_name": "video4",
				"display_name": "AppleTV"
			}
		]
	}]
}
]
}
Information from the log:
1. Homebridge log file showing relevant information. Experienced users are asked to turn debug on.
Hint: The more information you provide here, the easier it is to help you. Do NOT provide only a single line showing an error message - give the develpers a chance by providing a full log.
ERROR: Your configuration is missing the parameter "volume_dimmer". Assuming "false".
[4/30/2020, 10:16:45 PM] [Onkyo] ERROR: Your configuration is missing the parameter "filter_inputs". Assuming "false".
[4/30/2020, 10:16:46 PM] SyntaxError: Unexpected token ] in JSON at position 13
    at JSON.parse (<anonymous>)
    at OnkyoAccessory.createRxInput (/usr/lib/node_modules/homebridge-onkyo/index.js:241:19)
    at OnkyoAccessory.setUp (/usr/lib/node_modules/homebridge-onkyo/index.js:180:8)
    at new OnkyoAccessory (/usr/lib/node_modules/homebridge-onkyo/index.js:176:8)
    at /usr/lib/node_modules/homebridge-onkyo/index.js:36:22
    at Array.forEach (<anonymous>)
    at OnkyoPlatform.createAccessories (/usr/lib/node_modules/homebridge-onkyo/index.js:35:13)
    at new OnkyoPlatform (/usr/lib/node_modules/homebridge-onkyo/index.js:28:8)
    at /usr/lib/node_modules/homebridge/src/server.ts:396:40
    at Array.forEach (<anonymous>)

**Expected behavior**
Support TX-NR676
**Screenshots**

**Additional context**

**Comment by rosorrentino** [comment]
I can see the problem is with the dependency on https://github.com/ToddGreenfield/homebridge-onkyo/blob/master/package.json
I don't really understand how all this work but somehow I found it it's based on a project that is being maintained again at https://github.com/miracle2k/onkyo-eiscp
Can't you get something from there? (again, I am not sure)

**Comment by cbrandlehner** [comment]
@rosorrentino the hadware support comes from https://github.com/tillbaks/node-eiscp which is, unfortunately, not currently maintained.
The onkyo-eiscp project you linked looks promising, but is not a JavaScript library.

**Comment by solowalker27** [comment]
My PR https://github.com/ToddGreenfield/homebridge-onkyo/pull/80 includes an updated eiscp.js that I found which has support for the TX-NR676. You could test that PR or wait until it's merged.

**Comment by Tom2Drake** [comment]
How to test your PR? 

npm install -g git+https://github.com/solowalker27/homebridge-onkyo.git?

**Comment by solowalker27** [comment]
`npm install -g solowalker27/homebridge-onkyo#0.8.0` should do it.

https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly

**Comment by solowalker27** [comment]
Since this issue is stale and should/could have been resolved with an update, I'm closing this. If it's still a problem, reopen (or file a issue) and give updated details describing the problem and what version of the plug-in you're currently using.
