### ISSUE TITLE
Request support for Integra (Onkyo) DRX-5

### ISSUE THREAD

**Issue by fwav8r** [ToddGreenfield/homebridge-onkyo#77]
Kindly requesting added support for Integra (Onkyo) DRX-5 receiver. Homebridge-Onkyo already connects to my receiver with the default receiver type. Adding support would line up options to this requested receiver.

Thanks.
Mike A.

**Comment by solowalker27** [comment]
My PR https://github.com/ToddGreenfield/homebridge-onkyo/pull/80 includes an updated eiscp.js that I found that supports the DRX-5. You could test the PR or wait until it's merged.

**Comment by solowalker27** [comment]
Since this issue is stale and should/could have been resolved with an update, I'm closing this. If it's still a problem, reopen (or file a issue) and give updated details describing the problem and what version of the plug-in you're currently using.
