### ISSUE TITLE
require doesn't find eiscp-commands.json in HOOBS 3.2.4

### ISSUE THREAD

**Issue by pedrocadiz13** [ToddGreenfield/homebridge-onkyo#79]
The plugin fails to start, logs indicate that the following line files to find eiscp-commands.json.

let eiscpData = require('./node_modules/eiscp/eiscp-commands.json');

as a workaround I've  edited to full path to file /home/hoobs/.hoobs/etc/node_modules/eiscp/eiscp-commands.json

A permanent fix would be better, so that future updates don't overwrite.

**Comment by cbrandlehner** [comment]
@pedrocadiz13 Can you check if you have git installed?

**Comment by pedrocadiz13** [comment]
Yes, git version 2.20.1 is installed.
