### ISSUE TITLE
unable to install on raspberry pi

### ISSUE THREAD

**Issue by toshibochan** [ToddGreenfield/homebridge-onkyo#81]
please help.

npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/tillbaks/node-eiscp.git /root/.npm/_cacache/tmp/git-clone-1c87a8dc/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-1c87a8dc/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-24T07_13_45_827Z-debug.log

**Comment by zackdvd** [comment]
I had a similar error. started npm install from /tmp/ and that worked for me.

**Comment by jondthompson** [comment]
I installed initially via Homebridge UI without issue.
