### ISSUE TITLE
Unable to configure a receiver with 2 zones (as 2 receivers same IP Address)  

### ISSUE THREAD

**Issue by michaelpettorosso** [ToddGreenfield/homebridge-onkyo#82]
**Is your feature request related to a problem? Please describe.**
Unable to configure a receiver with 2 zones (as 2 receivers same IP Address)  

**Describe the solution you'd like**
EISCP doesn't allow more than one connection with same IP address 

I've manage to alter the code to get it to work

class OnkyoPlatform {
	constructor(log, config, api) {
		this.api = api;
		this.config = config;
		this.log = log;
		this.receivers = this.config.receivers;
		this.receiverAccessories = [];
                **this.connections = [];**

if (this.receivers === undefined) {
		this.log.error('ERROR: your configuration is incorrect. Configuration changed with version 0.7.x');
		this.receivers = '';
	}

this.createAccessories(this, this.receivers);
}

createAccessories(platform, receivers) {
	platform.numberReceivers = platform.receivers.length;
	platform.log.debug('Creating %s receivers...', platform.numberReceivers);
	if (platform.numberReceivers === 0) return;

receivers.forEach(receiver => {
	**if (!connections[receiver.ip_address]) 
	      {
	        this.log.debug('Creating new connection for ip ' = receiver.ip_address);
	        connections[receiver.ip_address] = require('eiscp');
	        connections[receiver.ip_address].connect({host: receiver.ip_address, reconnect: true, model: receiver.model});
	      }**
	const accessory = new OnkyoAccessory(platform, receiver);
	platform.receiverAccessories.push(accessory);
	});
}

accessories(callback) {
	callback(this.receiverAccessories);
}

Then in OnkyoAccesory I changed the assignment of eiscp to the following

**this.eiscp = platform.connections[this.ip_address];**

and removed the connect code

I've tested it with my receiver and I now have 2 receivers appearing in HomeKit

**Comment by jondthompson** [comment]
Has anyone incorporated @michaelpettorosso's code into the project yet? I'm running into the same issue in 0.8.0 on my 686

**Comment by jondthompson** [comment]
This should be marked resolved now.
