### ISSUE TITLE
Change device category to AUDIO_RECEIVER

### ISSUE THREAD

**Issue by ttimpe** [ToddGreenfield/homebridge-onkyo#83]
According to this: https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/57#issuecomment-694058114, it is possible to expose devices with the category of AudioReceiver. This should be a quick fix, but I don't know where to put.

**Comment by iondarie** [comment]
also interested in this!

**Comment by ttimpe** [comment]
Try my fork!

**Comment by iondarie** [comment]
ok, let me figure out how i can do that 👍

**Comment by jondthompson** [comment]
@ttimpe , if you have that fixed, can you send a pull request?
