### ISSUE TITLE
Onkyo range TX-RZ740/840 support

### ISSUE THREAD

**Issue by ahradnansky** [ToddGreenfield/homebridge-onkyo#85]
I use homebridge-onkyo with my TX-RZ740 but is defined as TX-NR609 type under homebridge.
What it would require to add native support for TX-RZ range as well?
Thx.

**Describe alternatives you've considered**

**Comment by solowalker27** [comment]
The plugin should support TX-RZ720 and TX-RZ820. Those should be pretty close to the 740/840. Try one of those and see if they work better for you. If they don't, you can reopen this or file a new issue with specific problems you're having.
