### ISSUE TITLE
Problem when using Philips Hue lights and Onkyo TX-NR686 in the same "Home App" room

### ISSUE THREAD

**Issue by brutus-downunder** [ToddGreenfield/homebridge-onkyo#86]
**Is your feature request related to a problem? Please describe.**
When using Hue lights and Onkyo in the same room "Living Room" and the Onkyo option "Show Volume as a Dimmer" is set to "true" when saying "Hey siri set living rooms lights to 50%" both the lights brightness and onkyo volume are set to 50%

**Describe the solution you'd like**
Change Onkyo "Show Volume as a Dimmer" to "Show Volume as a Fan". 

**Describe alternatives you've considered**
Putting the Onkyo in another Room "Lounge Room" but this is not convenient.
 
**Additional context**
I changed your index.js to test.
Line 891 `this.dimmer = new Service.Fan(this.name + ' Volume', 'dimmer');`
Line 907 `.addCharacteristic(Characteristic.RotationSpeed)`
this small change achieved my desired solution.
Maybe you could add code so this could be a configurable option i.e to use "Light" or "Fan" for "Show Volume as a ....."

**Comment by cbrandlehner** [comment]
I would like to hear some opinions from other users.

The code change seems to be simple and the use case is clear. However, is there any foreseeable risk?

**Comment by brutus-downunder** [comment]
Looks like opinions are few and far between.

Just wanted to say that if there was an option for Fan or Light then any "risk" would be negligible. There are other Onkyo npm's that use the fan/light option.

**Comment by cbrandlehner** [comment]
I am fine with going forward moving from dimmer to fan (speed). Are you going to submit a PR?

**Comment by brutus-downunder** [comment]
Created Pull Request - First time Pull Requester so hope I've done it right.
