### ISSUE TITLE
Support DRC-R1

### ISSUE THREAD

**Issue by ryanschmidt** [ToddGreenfield/homebridge-onkyo#9]
Great plugin! I'm only just getting into Homebridge and would love to automate my theater a bit more. My Integra DRC-R1 AVR isn't listed but I've got the basic ON/OFF functionality by using the recommended `TX-NR609`. Do you have another model you'd recommend I try (before I just start grabbing a few) or so you have any information on how to add models that I could somehow help contribute to?

Appreciate your work here. It's a great plugin regardless. Thanks!

**Comment by ToddGreenfield** [comment]
Hi Ryan. Thanks for the feedback. Unfortunately only the models listed in the referenced json file are valid. If yours works using one of them I would use that. Keep in mind that the Apple home app only shows on/off. You would need to use an app like Elgato Eve to use the other features like volume and input. You can create scenes though which then show up in the home app. Hopefully that will help you out.

**Comment by ryanschmidt** [comment]
Oh dang. So many more options within Eve. Thank you!

**Comment by ToddGreenfield** [comment]
Can we close this issue?
