### ISSUE TITLE
input selector bug on scene

### ISSUE THREAD

**Issue by toshibochan** [ToddGreenfield/homebridge-onkyo#92]
I have 4 input dvd, stem-box, video2 and video3. same in zone2
4 scenes:
watch 4k Apple TV(dvd), Watch office Apple TV(strm-box), watch jp Apple TV(video2) and watch fire tv(video3).

when I select scenes with stem-box or video2 or video3 it chance to correct input but second later always change by self to first input(DVD).

work okay when I select manually. this only happens when I use scenes.

            "receivers": [
                {
                    "name": "Main Onkyo",
                    "model": "TX-NR609",
                    "ip_address": "192.168.1.62",
                    "inputs": [
                        {
                            "input_name": "dvd",
                            "display_name": "APTV 4K"
                        },
                        {
                            "input_name": "video2",
                            "display_name": "APTV JP"
                        },
                        {
                            "input_name": "video3",
                            "display_name": "FireTV"
                        },
                        {
                            "input_name": "strm-box",
                            "display_name": "APTV Office"
                        }
                    ],
                    "default_input": "dvd",
                    "filter_inputs": true,
                    "default_volume": 42,
                    "max_volume": 60,
                    "volume_dimmer": true,
                    "map_volume_100": true,
                    "poll_status_interval": "3000",
                    "zone": "main"
                },
                {
                    "name": "Zone 2 Onkyo",
                    "model": "TX-NR609",
                    "ip_address": "192.168.1.62",
                    "inputs": [
                        {
                            "input_name": "dvd",
                            "display_name": "APTV 4K"
                        },
                        {
                            "input_name": "strm-box",
                            "display_name": "APTV Office"
                        },
                        {
                            "input_name": "video2",
                            "display_name": "APTV JP"
                        },
                        {
                            "input_name": "video3",
                            "display_name": "Fire TV"
                        }
                    ],
                    "default_input": "dvd",
                    "filter_inputs": true,
                    "default_volume": 42,
                    "max_volume": 60,
                    "volume_dimmer": true,
                    "map_volume_100": true,
                    "poll_status_interval": "3000",
                    "zone": "zone2"
                }
            ],
            "platform": "Onkyo"
        }
    ],

https://user-images.githubusercontent.com/15816913/103240376-0572b600-4905-11eb-9a4d-23a9ef85b917.mov

One more thing is Zone 2 name is not working. I have set as name "Zone 2 Onkyo" in config but in home app show name as TV and I have to change the name to "Zone 2 Onkyo" in home app.

**Comment by toshibochan** [comment]
look like is going to default input

**Comment by toshibochan** [comment]
if no set default input work okay

**Comment by solowalker27** [comment]
Default input is a feature where it will always go to that input when you turn on the receiver. So it sounds like it's working as expected. We'd have no way of telling if it's being turned on via a scene or not to decide whether to use the default input. The correct solution is to not use default input.
