### ISSUE TITLE
Combine Plugins

### ISSUE THREAD

**Issue by Albatros2409** [ToddGreenfield/homebridge-onkyo#96]
Thank you very much for the plugin. They're are more than one Onkyo plugins and was wondering if yours and one I tried could be combined to create a "certified" Onkyo homebridge plugin.

I tried using your plugin but had some issues with connection a Onkyo TX-NR5010. Then I tried another plugin, homebridge-onkyo-pioneer. It was quite easy in de Homebridge Plugin UI to configure and my receiver was directly recognized. 

Also the device had the icon of a receiver in the Home App. Very nice. Also adding the zone 2 was very easy. Also an error and zone 2 in the home app not updating on/off. So the plugin is under development but as far as I can see quite advanced. Not sure if the further development is on its way  but maybe you can combine the two.

https://github.com/nitaybz/homebridge-onkyo-pioneer#readme

**Comment by toshibochan** [comment]
@Albatros2409 Homebridge-onkyo-pioneer have input selector?

**Comment by Albatros2409** [comment]
In the Home App, yes.

**Comment by solowalker27** [comment]
We won't be combining plugins. You'll need to choose one or the other. I tried the other plugin for a while and also had connection stability issues. Not sure how to resolve that. And I think it would be too much work to refactor this one to do some auto discovery and accessory caching like the other plugin does. I'm sure if someone decided to do it we'd accept a PR.

The EISCP we're using says it supports the TX-NR5010. You could file issues about any particular problems you had.

Not having the icon for the receiver was a bug. I submitted a PR to fix it that was just merged and released.
