### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by mkulesh** [ToddGreenfield/homebridge-onkyo#97]
Hi, I am the author of "Enhanced Controller for Onkyo and Pioneer" (https://github.com/mkulesh/onpc) and I am looking for the latest ISCP documentation. The most actual release of the "Integra Serial Communication Protocol" that I have is version 1.40 (https://github.com/mkulesh/onpc/blob/master/doc/ISCP_AVR_140.xlsx). Do you have more actual release of this document? Thank you.

**Comment by solowalker27** [comment]
I haven't seen anything. I believe I went looking at one point but didn't find much recent. I might have even found your repo, as it looks familiar. But I'm not the one who originally wrote the functionality for this plugin. The one who did has long abandoned their project; this is a fork of a fork or something. I don't currently know where to find updated documentation.

**Comment by mkulesh** [comment]
Thank you for response. One month ago I found the version 146. If you need it, please look here:
https://github.com/mkulesh/onpc/blob/master/doc/ISCP_AVR_146.xlsx
