### ISSUE TITLE
Can't install homebridge-onkyo v2021.2.2 (2021-01-10).

### ISSUE THREAD

**Issue by Honosapiens** [ToddGreenfield/homebridge-onkyo#99]
**Confirm you have checked the WIKI for troubleshooting first**
_Fill out and check (`[x]`) the boxes which apply.
- Homebridge version: v1.3.1
- Plugin version: v2021.2.2
- OS, including release name/version: MacOS Big Sur

DIR: /usr/local
CMD: npm install -g homebridge-onkyo@latest

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t git://github.com/untitledlt/eiscp.js.git
npm ERR! 
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! exited with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jlrodz/.npm/_logs/2021-03-01T15_34_39_503Z-debug.log

Command failed. Please review log for details.

**Comment by cbrandlehner** [comment]
Have you installed the Command Line Package?
See here:
https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

**Comment by Honosapiens** [comment]
Thanks!  It did work!
